
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'A\x18\xce?=\xa2\xc7w\xeb4\xe6\xd6>\xdb|\x1a'
    
_lr_action_items = {'PAR_O':([0,2,5,6,],[2,2,2,2,]),'LETTER':([0,2,5,6,],[3,3,3,3,]),'$end':([1,3,4,8,9,10,],[0,-5,-1,-2,-3,-4,]),'ETOILE':([1,3,4,7,8,9,10,],[4,-5,-1,4,4,4,-4,]),'PLUS':([1,3,4,7,8,9,10,],[5,-5,-1,5,-2,-3,-4,]),'POINT':([1,3,4,7,8,9,10,],[6,-5,-1,6,6,-3,-4,]),'PAR_F':([3,4,7,8,9,10,],[-5,-1,10,-2,-3,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,6,],[1,7,8,9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression ETOILE','expression',2,'p_expression_etoile','C:\\Users\\Carré Vilmorin\\Desktop\\automate\\InstructionsTypographiques\\src\\expressionRationnelle_yacc.py',13),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','C:\\Users\\Carré Vilmorin\\Desktop\\automate\\InstructionsTypographiques\\src\\expressionRationnelle_yacc.py',17),
  ('expression -> expression POINT expression','expression',3,'p_expression_concatene','C:\\Users\\Carré Vilmorin\\Desktop\\automate\\InstructionsTypographiques\\src\\expressionRationnelle_yacc.py',21),
  ('expression -> PAR_O expression PAR_F','expression',3,'p_expression_paranthese','C:\\Users\\Carré Vilmorin\\Desktop\\automate\\InstructionsTypographiques\\src\\expressionRationnelle_yacc.py',25),
  ('expression -> LETTER','expression',1,'p_expression_letter','C:\\Users\\Carré Vilmorin\\Desktop\\automate\\InstructionsTypographiques\\src\\expressionRationnelle_yacc.py',29),
]
